on: push
jobs:
    print-version:
            runs-on: windows-latest
            steps:
                - run: node --version
    eslint:
        runs-on: windows-latest
        steps:
            - name: Checkout code 
            - uses: actions/checkout@v2
            - name: Install Node.js
            - uses: actions/setup-node@v2
                with: 
                    node-version: '18.15.0'
            - name: Install dependencies
            - run: npm install
            - name: Run ESLint
            - run: npx eslint .